### ISSUE TITLE
Can't download the jar file

### ISSUE THREAD

**Issue by rza313** [SecLab-Regensburg/InfluxDBConnector#1]
Good day, I wanted to try out your influxdb connector but wasn't able to download it as it's behind some authorization. Is there any way you could share a working link?

**Comment by gwutz** [comment]
Hi sure. I will have a look in the afternoon. I just have to went to work. I will write you when i am arrived.

**Comment by marove2000** [comment]
Morning. I've just updated the readme. The link was pointing to another gogs. Should work now.

**Comment by rza313** [comment]
Hi, thanks for your reply. I checked out the link and it's pointing to the zip files which contain the source. Do I have to build the jar myself? The readme mentions a single jar file. Thanks again, appreciate your time.

**Comment by gwutz** [comment]
Sorry for the inconvenience i just uploaded a drop in plugin for your usage. If there are errors i am happy if you can open an issue for that. I don't work anymore with influx but am happy to help.

**Comment by rza313** [comment]
Thanks again, I managed to successfully install the plugin
